# Chapter 2: Learning Python and solving algebraic equations
Introduction to the Phys212/Biol212 class
### by Ilya Nemenman, 2016-2020

Make sure you read Chapters 1 and 2 of the *Student Guide* before this notebook, and that you read Chapters 3 and 4 in parallel with this notebook. Make sure also that you in detail study the code for the cells that I provide below, not just the output of the cells. This is essential if you want to pick up on python programming quickly.

## Some Python practice 
Let's first pre-emptively review a few elements in Python coding that many of you probably will have problems with otherwise. 

### Assignments and comparisons
Let's execute the following code:

In [1]:
a = 0
a == 1
print (a)
a = 1
print(a)
b = (a == 1)
print(b)

0
1
True


Note that the first line above assigns the value of 0 to the variable `a`. The second line does not do the assignment, but instead compares `a` to 1. Since the result of the comparison is not stored anywhere, it disappears. We can verify that `a` was not changed by the comparison by simply printing it. The next line, in contrast, assigns 1 to `a`. We verify that this, in fact, happened by printing the variable. We again do the comparison of `a` to 1. Notice, however, that this time we store the result of this comparison in a variable $b$, which has the value of `True`, as we can see by printing it.

### Vector operations
You have created numpy arrays in your first lab. Why do we bother with this concept? Arrays allow us to perform vector operations -- instead of, for example, adding two arrays element by element, or copying an array element by element we can do either of these tasks in just one single operation. Let's see how this works.

In [2]:
import numpy as np #importing the numpy module

L = 10  # the size of the arrays we will create
a = np.arange(L)
b = np.ones(L)
print(a)
print(b)

c = a + b
print(c)

[0 1 2 3 4 5 6 7 8 9]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


Notice how we didn't have to create `c` separately, and in a single addition operation we were able to add all elements of `a` and `b` into `c`. Such vector operations are, of course, more elegant than doing the same element by element. Importantly, they are also faster. Let's verify this. To measure how long something takes, we need to load a new module `Time`.

In [3]:
import time
dir(time)

['_STRUCT_TM_ITEMS',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'altzone',
 'asctime',
 'clock',
 'ctime',
 'daylight',
 'get_clock_info',
 'gmtime',
 'localtime',
 'mktime',
 'monotonic',
 'monotonic_ns',
 'perf_counter',
 'perf_counter_ns',
 'process_time',
 'process_time_ns',
 'sleep',
 'strftime',
 'strptime',
 'struct_time',
 'time',
 'time_ns',
 'timezone',
 'tzname',
 'tzset']

>### Your turn 2.1
Explore what different functions in this module do.

We will be using the function `time.time()`, which return the time in seconds since the beginning of some standardized epoch as a floating point number. Notice that the function `time.time()` must be called with the parenthesis at the end. Indeed, let's try:

In [4]:
print(time.time)
print(time.time())

<built-in function time>
1579790522.700278


>### Your turn 2.2
Explain the results of the Python output above.

Now let's see how long vector and non-vector versions of the same operations take. 

In [5]:
L = 100000        # length of the vectors we will operate with
a = np.arange(L)  # creating these long vectors
b = np.ones(L)

# now let's add a and b as a vector  operation and see how long it takes
t = time.time()   # store the current time in the variable t
c = a+b
print ('The vector addition took', time.time()-t, 'sec.')

The vector addition took 0.0016257762908935547 sec.


>### Your turn 2.3
Run the cell above multiple times. Does it always time the same duration of time to execute the same command?

Now let's do the same operation using element by element addition.

In [6]:
t = time.time()  # store the current time in the variable t

c = np.zeros(L)  # preallocate memory for an empty array
for i in np.arange(L):  # do element-by-element addition
    c[i] = a[i] + b[i]
    
print ('Element by element addition with pre-allocated memory took', time.time() - t, 'sec.')

Element by element addition with pre-allocated memory took 0.3539109230041504 sec.


Notice how much longer it took to execute the same operation. But this is not the worst. Let's try the following.

In [7]:
t = time.time()  # store the current time in the variable t

c = np.arange(0) # create a null array (array with no elements)
print(c)

for i in np.arange(L): # do element-by-element addition while growing the array
    c = np.hstack((c, a[i] + b[i]))
    
print ('Element by element addition with pre-allocated memory took', time.time() - t, 'sec.')

[]
Element by element addition with pre-allocated memory took 3.1772260665893555 sec.


>### Your turn 2.4
Why do we use double perentheses ((...)) in the call to `np.hstack()`?

Why does this happen? The vector operations are the fastest -- they are encoded using low-level computer language, and are optimized internally. The element-wise edition takes longer because at every point in the cycle the Python interpreter has to do a variety of checks, such as is `a` an array? Does it have an element `i`? And the same for `b` and `c`, and all of this takes time. Finally, in the third version, every time we stack the arrays together, a new array gets created. **We will discuss this in class in more detail, and I wil add a figure later to explain this.**

## Solving a quadratic equation

Let's say we want to solve a quadratic equation $$ax^2+bx+c=0.$$ The two solutions of this are given by $$x_{1,2}=\frac{-b\pm \sqrt{b^2-4ac}}{2a},$$
where $D=b^2-4ac$ is called the discriminant. Let's write a short script to solve this. 

We start with the initialization block. Normally we would import `numpy` and other modules here as well, but now we do not need to do this, this numpy was just imported above.

In [8]:
a = 1.0  #initializing parameter values
b = 2.0
c = -2.0

Now we calculate the square root of the determinant using the `numpy.np` function, and print the two roots.

In [9]:
sD = np.sqrt(b**2-4*a*c)
x1 = (-b+sD)/(2*a)
x2 = (-b-sD)/(2*a)

print(x1)
print(x2)

0.7320508075688772
-2.732050807568877


This code would work well often, but not always. For example, change `c` to 2.0 above and rerun the cell. What happened? This introduces the idea of checking of exceptions: what if the discriminant is zero? or negative? or if `a` is equal to 0? 

>### Your turn 2.5
Change the code for solving the quadratic equations to address all possible exceptions you can think of, so that the code runs for all values of the parameters `a`, `b`, and `c`. 

>### Track 2
Rewrite the code above to work with complex numbers.

>### Your turn 2.6
Additional exercise: Evaluate a binary log (log base 2) of a number 42 using at least three different sets of commands imported from `numpy`. Verify your result by taking 2 to the appropriate power and seeing if you get 42 back. For this, you will need to remind yourself how logarithms with different bases relate to each other.

## More to come